services:
  mysql:
    image: mysql:8
    container_name: voting-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: voter_db
      MYSQL_USER: voter_app
      MYSQL_PASSWORD: voter_app_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
